'use strict';

const ACCOUNT_STATUS = Object.freeze({
  ACTIVE:'ACTIVE', VOID:'VOID', RESTRICTED:'RESTRICTED',
  TERMINATED:'TERMINATED', CLOSED:'CLOSED', LEGAL:'LEGAL',
  TEMP_DISCONNECTED:'TEMP_DISCONNECTED',
});

const INVOICE_TYPE = Object.freeze({
  STANDARD:'STANDARD', ADJUSTMENT:'ADJUSTMENT', MANUAL:'MANUAL',
  ESTIMATED:'ESTIMATED', CREDIT_NOTE:'CREDIT_NOTE', DEBIT_NOTE:'DEBIT_NOTE',
  METER_CHANGE:'METER_CHANGE',
});

const INVOICE_STATUS = Object.freeze({
  OPEN:'OPEN', PARTIAL:'PARTIAL', CLEARED:'CLEARED', REVERSED:'REVERSED',
  CANCELLED:'CANCELLED', DISPUTED:'DISPUTED', HELD:'HELD', HELD_NO_TIN:'HELD_NO_TIN',
});

const SOURCE_SYSTEM = Object.freeze({
  SIBMA:'SIBMA', IWRS:'IWRS', MANUAL:'MANUAL',
  BULK_PAYMENT:'BULK_PAYMENT', AGENT_IMPORT:'AGENT_IMPORT', BTP_INTERNAL:'BTP_INTERNAL',
});

const PAYMENT_CHANNEL = Object.freeze({
  // iWRS-originated (counter payments — Scenario 2.5)
  COUNTER_CASH:'COUNTER_CASH', COUNTER_CHEQUE:'COUNTER_CHEQUE', COUNTER_CARD:'COUNTER_CARD',
  // Direct inbound — bank or third-party files (Scenarios 4.1, 4.4, 4.5)
  JOMPAY:'JOMPAY', AGENT_COLLECTION:'AGENT_COLLECTION', BAYARAN_PUKAL:'BAYARAN_PUKAL',
  // AR Hub bidirectional (Scenarios 4.2, 4.3)
  DUITNOW_QR:'DUITNOW_QR', EMANDATE:'EMANDATE',
  // Customer self-service (Scenario 4.6A — direct FPX webhook to AR Hub)
  FPX:'FPX',
  // Other
  MANUAL_EFT:'MANUAL_EFT', SYSTEM_TRANSFER:'SYSTEM_TRANSFER',
});

const PAYMENT_STATUS = Object.freeze({
  RECEIVED:'RECEIVED', CLEARING_PENDING:'CLEARING_PENDING',
  ALLOCATED:'ALLOCATED', PARTIALLY_ALLOCATED:'PARTIALLY_ALLOCATED',
  UNALLOCATED:'UNALLOCATED', REVERSED:'REVERSED', BOUNCED:'BOUNCED', CHARGEBACK:'CHARGEBACK',
});

const DUNNING_LEVEL = Object.freeze({
  CURRENT:0, FIRST_REMINDER:1, FINAL_NOTICE:2, DISCONNECTION_NOTICE:3, DISCONNECTED:4,
  LEGAL_ACTION:5,
});

const DUNNING_THRESHOLDS = Object.freeze({ LEVEL_1:14, LEVEL_2:30, LEVEL_3:45, LEVEL_4:60, LEVEL_5:90 });

const DEPOSIT_STATUS = Object.freeze({
  HELD:'HELD', REFUNDED:'REFUNDED', APPLIED_TO_BALANCE:'APPLIED_TO_BALANCE',
  DORMANT:'DORMANT', TRANSFERRED_UNCLAIMED:'TRANSFERRED_UNCLAIMED',
});

const GL_POSTING_STATUS = Object.freeze({
  PREPARED:'PREPARED', SUBMITTED:'SUBMITTED', ACCEPTED:'ACCEPTED',
  REJECTED:'REJECTED', FAILED:'FAILED', RETRY_PENDING:'RETRY_PENDING',
});

const CLEARING_TYPE = Object.freeze({
  FIFO:'FIFO', REFERENCE_MATCH:'REFERENCE_MATCH', EXACT_MATCH:'EXACT_MATCH',
  MANUAL:'MANUAL', OVERPAYMENT_CREDIT:'OVERPAYMENT_CREDIT',
});

const ADJUSTMENT_TYPE = Object.freeze({
  METER_READ_CORRECTION:'METER_READ_CORRECTION', LEAKAGE:'LEAKAGE',
  BILLING_ERROR:'BILLING_ERROR', TARIFF_RECLASSIFICATION:'TARIFF_RECLASSIFICATION',
  GOODWILL_CREDIT:'GOODWILL_CREDIT', REGULATORY:'REGULATORY',
  PARTIAL_PERIOD:'PARTIAL_PERIOD', OTHER:'OTHER',
});

const WRITEOFF_THRESHOLDS = Object.freeze({
  SUPERVISOR: 50.00,  // MOCK: confirm with SAINS Finance during Blueprint
  MANAGER: 500.00,    // MOCK: confirm with SAINS Finance during Blueprint
  CFO: 5000.00,       // MOCK: confirm with SAINS Finance during Blueprint
  BOARD: 20000.00,    // MOCK: confirm with SAINS Finance during Blueprint
});

const FRAUD_ALERT_PATTERN = Object.freeze({
  DOUBLE_WRITEOFF:'DOUBLE_WRITEOFF', LARGE_ADJUSTMENT:'LARGE_ADJUSTMENT',
  QUICK_REVERSAL:'QUICK_REVERSAL', REFUND_NO_BILLING:'REFUND_NO_BILLING',
  DUPLICATE_BANK_ACCOUNT:'DUPLICATE_BANK_ACCOUNT',
  ADDRESS_PAYMENT_CHANGE:'ADDRESS_PAYMENT_CHANGE', SELF_PAYMENT:'SELF_PAYMENT',
  DEPOSIT_NO_CLOSURE:'DEPOSIT_NO_CLOSURE',
  BULK_WRITEOFF_SAME_USER:'BULK_WRITEOFF_SAME_USER', AGENT_BATCH_ANOMALY:'AGENT_BATCH_ANOMALY',
  UNUSUAL_PAYMENT_PATTERN:'UNUSUAL_PAYMENT_PATTERN', // Payment > 5× account average
  RAPID_ACCOUNT_CHANGES:'RAPID_ACCOUNT_CHANGES',     // > 3 change requests in 7 days
  GHOST_ACCOUNT_PAYMENT:'GHOST_ACCOUNT_PAYMENT',     // Payment to VOID/CLOSED account
});

const VULNERABILITY_CATEGORIES = Object.freeze([
  'OKU',                    // Orang Kurang Upaya (disabled)
  'WARGA_EMAS',             // Senior citizen
  'IBU_TUNGGAL',            // Single mother
  'BERPENDAPATAN_RENDAH',   // Low income (B40)
  'KANAK_KANAK',            // Child-headed household
  'PENYAKIT_KRONIK',        // Chronic illness
  'OTHER',
]);

const OVERPAYMENT_NOTIFY_THRESHOLD = 50.00;
const GL_POSTING_MAX_RETRIES = 3;
const EINVOICE_CANCEL_WINDOW_HOURS = 72;
const CHEQUE_CLEARANCE_BUSINESS_DAYS = 3;  // CRITICAL-11

const SAP_CORE = Object.freeze({
  COMPANY_CODE: '9001', // MOCK: confirm actual company code with SAINS Finance during Blueprint
  JOURNAL_ENTRY_API_PATH: '/sap/opu/odata/sap/API_JOURNALENTRYITEMBASIC_SRV',
  BUSINESS_PARTNER_API_PATH: '/sap/opu/odata/sap/API_BUSINESS_PARTNER',
  COMMUNICATION_SCENARIO: 'SAP_COM_0002',
  CURRENCY: 'MYR',
  DOCUMENT_TYPE_AR: 'SA',
});

// MOCK: confirm actual cost centre codes with SAINS Finance
const BRANCH_COST_CENTRE = Object.freeze({
  SEREMBAN:    'CC-SRM', // MOCK: confirm actual cost centre codes with SAINS Finance during Blueprint
  NILAI:       'CC-NLI', // MOCK: confirm actual cost centre codes with SAINS Finance during Blueprint
  PORT_DICKSON:'CC-PDK', // MOCK: confirm actual cost centre codes with SAINS Finance during Blueprint
  JELEBU:      'CC-JLB', // MOCK: confirm actual cost centre codes with SAINS Finance during Blueprint
  JEMPOL:      'CC-JMP', // MOCK: confirm actual cost centre codes with SAINS Finance during Blueprint
  KUALA_PILAH: 'CC-KPH', // MOCK: confirm actual cost centre codes with SAINS Finance during Blueprint
  REMBAU:      'CC-RMB', // MOCK: confirm actual cost centre codes with SAINS Finance during Blueprint
});

const AGING_BUCKETS = Object.freeze([
  { code:'D0_30',    fromDays:0,   toDays:30   },
  { code:'D31_60',   fromDays:31,  toDays:60   },
  { code:'D61_90',   fromDays:61,  toDays:90   },
  { code:'D91_180',  fromDays:91,  toDays:180  },
  { code:'D181_365', fromDays:181, toDays:365  },
  { code:'D366_730', fromDays:366, toDays:730  },
  { code:'OVER_730', fromDays:731, toDays:null },
]);

const DEFAULT_PROVISION_RATES = Object.freeze({
  'D0_30_DOM':0.00,'D0_30_COM_S':0.00,'D0_30_COM_L':0.00,'D0_30_IND':0.00,'D0_30_GOV':0.00,
  'D31_60_DOM':0.02,'D31_60_COM_S':0.01,'D31_60_COM_L':0.01,'D31_60_IND':0.005,'D31_60_GOV':0.00,
  'D61_90_DOM':0.05,'D61_90_COM_S':0.03,'D61_90_COM_L':0.03,'D61_90_IND':0.02,'D61_90_GOV':0.00,
  'D91_180_DOM':0.15,'D91_180_COM_S':0.10,'D91_180_COM_L':0.10,'D91_180_IND':0.08,'D91_180_GOV':0.05,
  'D181_365_DOM':0.40,'D181_365_COM_S':0.30,'D181_365_COM_L':0.30,'D181_365_IND':0.25,'D181_365_GOV':0.15,
  'D366_730_DOM':0.75,'D366_730_COM_S':0.60,'D366_730_COM_L':0.60,'D366_730_IND':0.55,'D366_730_GOV':0.40,
  'OVER_730_DOM':1.00,'OVER_730_COM_S':0.90,'OVER_730_COM_L':0.90,'OVER_730_IND':0.85,'OVER_730_GOV':0.75,
});

const PTP_LIMITS = Object.freeze({
  MAX_DURATION_DAYS: 14,
  MAX_PER_YEAR_WITHOUT_ESCALATION: 3,
  MAX_PER_YEAR_WITH_MANAGER: 12,
});

const PAYMENT_PLAN_LIMITS = Object.freeze({
  MINIMUM_BALANCE: 100.00,
  MAX_DURATION_MONTHS: 6,
  EXTENDED_DURATION_MONTHS: 12,
  SUPERVISOR_MAX_MONTHS: 6,
  MANAGER_MAX_MONTHS: 12,
});

const FRAUD_THRESHOLDS = Object.freeze({
  ADJUSTMENT_PERCENT_OF_INVOICE: 0.50,
  QUICK_REVERSAL_DAYS: 3,
  REFUND_NO_BILLING_MONTHS: 6,
  ADDRESS_PAYMENT_CHANGE_DAYS: 7,
  BULK_WRITEOFF_SAME_USER_COUNT: 3,
  AGENT_ANOMALY_MULTIPLIER: 1.5,
  THIRD_PARTY_MULTI_ACCOUNT: 5,
});

const VALID_BRANCH_CODES = Object.freeze([
  'SRB', 'NLI', 'PDK', 'JLB', 'JMP', 'KPH', 'RMB', 'GMC', 'HQ',
  'SEREMBAN', 'NILAI', 'PORT_DICKSON', 'JELEBU', 'JEMPOL', 'KUALA_PILAH', 'REMBAU', 'GEMENCHEH',
]); // MOCK: confirm complete branch code list with SAINS Operations

const ADJUSTMENT_GL_IMMEDIATE = process.env.ADJUSTMENT_GL_IMMEDIATE === 'true';

const SUSPENSE_GL_ACCOUNT = '125000'; // MOCK: confirm suspense clearing GL with SAINS Finance
const PAAB_LIABILITY_GL   = '240000'; // MOCK: confirm PAAB liability GL
const PAAB_PAYABLE_GL     = '250000'; // MOCK: confirm PAAB payable GL
const PROVISION_GL        = '160000'; // MOCK: confirm provision GL account with SAINS Finance during Blueprint
const BAD_DEBT_EXPENSE_GL = '700000'; // MOCK: confirm bad debt expense GL account with SAINS Finance during Blueprint

module.exports = {
  ACCOUNT_STATUS, INVOICE_TYPE, INVOICE_STATUS, SOURCE_SYSTEM,
  PAYMENT_CHANNEL, PAYMENT_STATUS, DUNNING_LEVEL, DUNNING_THRESHOLDS,
  DEPOSIT_STATUS, GL_POSTING_STATUS, CLEARING_TYPE, ADJUSTMENT_TYPE,
  WRITEOFF_THRESHOLDS, FRAUD_ALERT_PATTERN, OVERPAYMENT_NOTIFY_THRESHOLD,
  GL_POSTING_MAX_RETRIES, EINVOICE_CANCEL_WINDOW_HOURS, CHEQUE_CLEARANCE_BUSINESS_DAYS,
  SAP_CORE, BRANCH_COST_CENTRE, AGING_BUCKETS, DEFAULT_PROVISION_RATES,
  PTP_LIMITS, PAYMENT_PLAN_LIMITS, FRAUD_THRESHOLDS,
  SUSPENSE_GL_ACCOUNT, PAAB_LIABILITY_GL, PAAB_PAYABLE_GL,
  PROVISION_GL, BAD_DEBT_EXPENSE_GL,
  ADJUSTMENT_GL_IMMEDIATE,
  VALID_BRANCH_CODES,
  VULNERABILITY_CATEGORIES,
};
